##############################################
# Meow Experience Plugin Configuration File  #
# Create by MeowCat Studio MlgmXyysd.        #
# @author MeowCat Studio MlgmXyysd           #
# @lastupdatetime 2019/05/31                 #
# Copyright (C) 2014-2019 MeowCat Studio     #
# Powered by MlgmXyysd All Rights Reserved.  #
##############################################

# Plugin Configuration
configuration:
  # Enable plugin auto check update <Boolean>
  # Only check, not download.
  update-check: false
  # Enable plugin update notification to op <Boolean>
  # when op join game.
  # You can disable notification with permission org.meowcat.essential.update
  update-message: false
  # Plugin language <String>
  # Must be found in /plugin/MeowEssential/language/<language>.yml
  language: en-us
  # Enable plugin command permissions <Boolean>
  # Set it to false and make all command can execute without permissions.
  permissions-enabled: false
  # Default section
  default-section:
    # Teleport default section <Boolean>
    # Player also can use /toggle to change.
    teleport: true
    # Call default section <Boolean>
    # Player also can use /toggle to change.
    call: true
    # Repeater default section <Boolean>
    # Player also can use /toggle to change.
    repeater: true
  # Enable auto clear entity with /kill <Boolean>
  auto-clear-entity: true
  # Auto clear entity delay tick (20*seconds) <long>
  auto-clear-entity-delay: 60000
  # Entity clear list <String[]>
  # Used for auto & manually clear
  # format: (- "namespace:entityName")
  # e.g.:- "minecraft:zombie"
  entity-clear-list:
    - "minecraft:zombie"
    - "minecraft:skeleton"
    - "minecraft:creeper"
    - "minecraft:spider"
  # Sound of AT <String>
  # Must be found in org.bukkit.Sound.
  sound-at: "ENTITY_PLAYER_LEVELUP"
  # Sound of AT (All player) <String>
  # Must be found in org.bukkit.Sound.
  sound-at-all: "ENTITY_PLAYER_LEVELUP"
  # Sound of AT (All player) <String>
  # Must be found in org.bukkit.Sound.
  sound-tpa: "ENTITY_PLAYER_LEVELUP"
  # Sound of AT (All player) <String>
  # Must be found in org.bukkit.Sound.
  sound-tpa-here: "ENTITY_PLAYER_LEVELUP"