##############################################
# Meow Experience Plugin Configuration File  #
# Create by MeowCat Studio MlgmXyysd.        #
# @author MeowCat Studio MlgmXyysd           #
# @lastupdatetime 2020/08/21                 #
# Copyright (C) 2013-2020 MeowCat Studio     #
# Powered by MlgmXyysd All Rights Reserved.  #
##############################################

# Plugin Configuration
configuration:
  # Enable plugin auto check update <Boolean>
  # Only check, not download.
  update-check: true
  # Enable plugin update notification to op <Boolean>
  # when op join game.
  # You can disable notification with permission org.meowcat.essential.update
  update-message: true
  # Plugin language <String>
  # Must be found in /plugin/MeowEssential/language/<language>.yml
  language: en-us
  # Enable plugin command permissions <Boolean>
  # Set it to false and make all command can execute without permissions.
  permissions-enabled: true
  # Default section
  default-section:
    # Teleport default section <Boolean>
    # Player also can use /toggle to change.
    teleport: true
    # Call default section <Boolean>
    # Player also can use /toggle to change.
    call: true
    # Repeater default section <Boolean>
    # Player also can use /toggle to change.
    repeater: false
  # Color placeholder <String>
  color-placeholder: "&"
  # Skin server textures root <String>
  skin-root: "http://localhost/textures/"
  # Enable auto clear entity with /kill <Boolean>
  auto-clear-entity: false
  # Auto clear entity delay tick (20*seconds) <long>
  auto-clear-entity-delay: 60000
  # Entity clear list <String[]>
  # Used for auto & manually clear
  # format: (- "namespace:entityName")
  # e.g.:- "minecraft:zombie"
  entity-clear-list:
    - "minecraft:zombie"
    - "minecraft:skeleton"
    - "minecraft:creeper"
    - "minecraft:spider"
  # Explode block config
  explode-block:
    # Creeper
    CREEPER:
      # Enable Creeper explode block <Boolean>
      enabled: false
      # Effective world <String[]>
      # format: (- "worldName")
      # e.g.:- "world"
      world:
        - "world"
    # TNT
    TNT:
      enabled: false
      world:
        - "world"
    # TNT Minecart
    TNT_MINECART:
      enabled: false
      world:
        - "world"
    # Wither regen explode
    WITHER:
      enabled: false
      world:
        - "world"
    # Wither skull
    WITHER_SKULL:
      enabled: false
      world:
        - "world"
    # Ghast fireball
    FIREBALL:
      enabled: false
      world:
        - "world"
    # Ender crystal
    END_CRYSTAL:
      enabled: false
      world:
        - "world"
  # Random teleport range
  teleport-random:
    # range X min <int>
    X-min: -500
    # range X max <int>
    X-max: 500
    # range Z min <int>
    Z-min: -500
    # range Z max <int>
    Z-max: 500
    # Random teleport worlds list <String[]>
    # Allow these world to use random teleport
    # format: (- "worldName")
    # e.g.:- "world"
    world-list:
      - "world"
  # Sound of AT <String>
  # Must be found in org.bukkit.Sound.
  sound-at: "ENTITY_PLAYER_LEVELUP"
  # Sound of AT (All player) <String>
  # Must be found in org.bukkit.Sound.
  sound-at-all: "ENTITY_PLAYER_LEVELUP"
  # Sound of tpa <String>
  # Must be found in org.bukkit.Sound.
  sound-tpa: "ENTITY_PLAYER_LEVELUP"
  # Sound of tpa (here) <String>
  # Must be found in org.bukkit.Sound.
  sound-tpa-here: "ENTITY_PLAYER_LEVELUP"